services:
  collector:
    image: otel/opentelemetry-collector:0.107.0
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - './smoke-tests/collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml'
      - './smoke-tests/collector:/var/lib'
    ports:
      - '4318:4318'
  mock-server:
    build:
      context: .
      dockerfile: ./Dockerfile.mock-server
    image: hny/custom-ios-mock-server
    ports:
      - '1080:1080'
