
version: 2.1

orbs:
  macos: circleci/macos@2

jobs:
  lint:
    macos:
      xcode: 16.1.0
    resource_class: macos.m1.medium.gen1

    steps:
      - checkout
      - run: make lint

  tests:
    macos:
      xcode: 15.4.0
    resource_class: macos.m1.medium.gen1

    steps:
      - macos/preboot-simulator:
          version: "17.5"
          platform: "iOS"
          device: "iPhone 15"
      - checkout
      - run: xcodebuild -version
      - run: xcodebuild test -scheme HoneycombTests -sdk iphonesimulator17.5 -destination 'OS=17.5,name=iPhone 15'

workflows:
  lint:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - lint

  unit-tests:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - tests

