receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  file:
    path: /var/lib/data.json
  logging:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: DEBUG
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, logging]
